//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickPos
        {
            get
            {
                return SteamVR_Actions.default_JoystickPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabL
        {
            get
            {
                return SteamVR_Actions.default_GrabL;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabR
        {
            get
            {
                return SteamVR_Actions.default_GrabR;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RjoystickPos
        {
            get
            {
                return SteamVR_Actions.default_RjoystickPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerL
        {
            get
            {
                return SteamVR_Actions.default_TriggerL;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerR
        {
            get
            {
                return SteamVR_Actions.default_TriggerR;
            }
        }
        
        public virtual SteamVR_Action_Boolean guideLineL
        {
            get
            {
                return SteamVR_Actions.default_guideLineL;
            }
        }
        
        public virtual SteamVR_Action_Boolean guideLineR
        {
            get
            {
                return SteamVR_Actions.default_guideLineR;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticR
        {
            get
            {
                return SteamVR_Actions.default_HapticR;
            }
        }
    }
}
